version: '3'

services:
  prisma-api-pgsql:
    image: postgres:11
    container_name: prisma-api-pgsql
    hostname: prisma-api-pgsql
    env_file: .env
    volumes:
    - pgsql-data:/var/lib/postgresql/data
    # - ./database/structure.sql:/docker-entrypoint-initdb.d/10-prisma_api.sql
    networks:
    - pgsql-network

  pgsql-cli:
    image: pygmy/pgcli
    container_name: pgsql_cli
    command: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST/$POSTGRES_DB
    stdin_open: true
    tty: true
    links:
    - prisma-api-pgsql
    volumes:
    - pgsqlcli-home:/root
    networks:
    - pgsql-network

  prisma-api:
    build:
      context: ./docker
    container_name: prisma-api
    hostname: prisma-api
    command: yarn start:dev
    working_dir: /app
    tty: true
    env_file: .env
    ports:
    - $API_PORT:$API_PORT
    volumes:
    - .:/app:delegated
    - home:/home/node
    links:
    - prisma-api-pgsql
    networks:
    - pgsql-network

volumes:
  pgsql-data:
  pgsqlcli-home:
  home:

networks:
  pgsql-network:
